[package]
name = "spelchek"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
crossterm = "0.27.0"
home = "0.5.9"
priority-queue = "1.4.0"
ratatui = "0.26.0"
